#
# Makefile for the Mstar MSG2388 touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_MSTAR_V33) 	+= mstar_drv_common.o \
					   mstar_drv_ic_fw_porting_layer.o \
					   mstar_drv_main.o \
					   mstar_drv_qcom.o \
					   mstar_drv_fw_control.o \
					   mstar_drv_mp_test.o \
					   mstar_drv_utility_adaption.o \
					   mstar_drv_platform_interface.o \
					   mstar_drv_platform_porting_layer.o \

