#
# Makefile for the Mstar MSG2xxx touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_COMMON_MSG2xxx) += mstar_drv_common.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_IC_FW_PORTING_LAYER_MSG2xxx) += mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_MAIN_MSG2xxx) += mstar_drv_main.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_QCOM_MSG2xxx) += mstar_drv_qcom.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_SELF_FW_CONTROL_MSG2xxx) += mstar_drv_self_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_SELF_MP_TEST_MSG2xxx) += mstar_drv_self_mp_test.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_UTILITY_ADAPTION_MSG2xxx) += mstar_drv_utility_adaption.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_PLATFORM_INTERFACE_MSG2xxx) += mstar_drv_platform_interface.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_PLATFORM_PORTING_LAYER_MSG2xxx) += mstar_drv_platform_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_MSTAR_DRV_JNI_INTERFACE_MSG2xxx) += mstar_drv_jni_interface.o