ccflags-y += -Idrivers/media/platform/msm/camera_a16c3h_v2
ccflags-y += -Idrivers/media/platform/msm/camera_a16c3h_v2/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_a16c3h_v2/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
